### ISSUE TITLE
Find test cases using glob and print their names

### ISSUE THREAD

**Issue by vduseev** [vduseev/tad#10]
## Demo

For config

```yaml
command: echo "A"
input: cases/input*.txt
output: cases/output*.txt
```

And file structure

```
tad.yml
cases/
  input01.txt
  input02.txt
  output01.txt
  output02.txt
```

Using command

```shell
tad
```

Print all test pair names

```shell
01
02
```
