### ISSUE TITLE
Launch child process from "command" for each test case and check return code

### ISSUE THREAD

**Issue by vduseev** [vduseev/tad#11]
## Demo

For config

```yaml
command: echo "A"
input: cases/input*.txt
output: cases/output*.txt
```

And command

```shell
tad
```

Print

```shell
Tests passed
==========
[x] 01
[x] 02
```

## Dependencies

* #10
