### ISSUE TITLE
Basic program that read configuration and displays it

### ISSUE THREAD

**Issue by vduseev** [vduseev/tad#9]
## Demo

For config file `tad.yaml`

```yaml
command: echo "a"
input:
output:
```

This invocation

```shell
tad
```

Should output these left padded values

```shell
     command: echo "a"
       input: null
      output: null
```
